# name: API Build and Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Setup Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.12'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Run Unit Tests
#         run: |
#           python -m pytest tests/

#       - name: Build API
#         run: |
#           uvicorn main:app --host 0.0.0.0 --port 8080 --reload

#       - name: Deploy to Streamlit Cloud
#         run: |
#           streamlit deploy streamlit_app/streamlit_classifier.py



name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn joblib scikit-learn pydantic streamlit requests
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Run FastAPI server
      run: |
        nohup uvicorn main:app --host 0.0.0.0 --port 8000 &

    - name: Deploy to Streamlit
      uses: streamlit/action@v1
      with:
        streamlit_app_path: streamlit_classifier.py
      env:
        PREDICTION_API_URL: http://localhost:8000/predict

